#! /bin/bash

set -e

TMPBASE=$(mktemp -d)
cleanup() {
    rm -rf "${TEMPBASE}"
}
trap cleanup EXIT


section() {
    printf "\n\n"
    echo "-----" "$@"
    printf "\n\n"
}


run_adb() {
    adb -s "$PHONE_ADB_SERIAL_NUMBER" "$@"
}


# This is invisible inside functions.
FIRSTARG="$1"

determine_device_serial_number() {
    # If a serial number was specified on the command line, use it.
    if [ -n "$FIRSTARG" ]
    then
	PHONE_ADB_SERIAL_NUMBER="$FIRSTARG"
	return
    fi
    
    DEVLIST="${TMPBASE}/devlist"

    adb devices | awk '$2 == "device" { print $1 }' > "${DEVLIST}"
    case $(wc -l "${DEVLIST}" | awk '{ print $1 }') in
	0)
	    echo "ERROR: No devices connected." 1>&2
	    exit 1
	    ;;
	1)
	    PHONE_ADB_SERIAL_NUMBER=$(cat "${DEVLIST}")
	    ;;
	*)
	    echo "ERROR: Multiple devices connected.  Specify one on the command line:" 1>&2
	    sed -e 's/^/    /' "${DEVLIST}"
	    exit 1
	    ;;
    esac
}

    

check_phone_is_connected() {
    if ! adb devices | grep --silent "$PHONE_ADB_SERIAL_NUMBER"; then
        echo "ERROR: device '${PHONE_ADB_SERIAL_NUMBER}' is not connected" 1>&2
        exit 1
    fi
}

check_phone_is_in_fastboot_mode() {
    # TODO: check if sudo is neded; udev may have been set up.
    sudo fastboot devices | grep --silent "$PHONE_ADB_SERIAL_NUMBER"
}


check_phone_is_in_adb_mode() {
    if run_adb shell true 2>/dev/null
    then
	return 0
    else
	return 1
    fi
}


extract_boot_image_on_phone() {
    section Extracting boot image
    enable_adb_root_access
    # TODO: Need to handle devices with only one slot.
    BOOT_SUFFIX=$(adb shell 'bootctl get-suffix $(bootctl get-current-slot)')
    PHONE_DOWNLOAD_DIR="/sdcard/Download"
    UNPATCHED_IMAGE="${PHONE_DOWNLOAD_DIR}/lineage-upgrade-boot.img"
    adb shell rm -rf "${UNPATCHED_IMAGE}"
    adb shell dd "if=/dev/block/by-name/boot${BOOT_SUFFIX}" "of=${UNPATCHED_IMAGE}"
}


patch_boot_image_on_phone() {
    section Patching boot image
    ADB_MAGISK="/data/adb/magisk"
    run_adb shell "${ADB_MAGISK}/boot_patch.sh" "${UNPATCHED_IMAGE}"
    PATCHED_IMAGE="/sdcard/Download/lineage-upgrade-boot-patched.img"
    run_adb shell rm -rf "${UNPATCHED_IMAGE}"
    run_adb shell mv "${ADB_MAGISK}/new-boot.img" "${PATCHED_IMAGE}"
}

transfer_patched_boot_image_to_pc() {
    section Downloading patched image
    PATCHED_IMAGE_LOCAL="${TMPBASE}/patched.img"
    run_adb pull "${PATCHED_IMAGE}" "${PATCHED_IMAGE_LOCAL}"
}


wait_for_phone_to_be_in_adb() {
    SECONDS=0
    until check_phone_is_in_adb_mode; do

	if [ "$SECONDS" -eq 0 ]
	then
	    printf 'Waiting for ADB.'
	fi

        if ((SECONDS > 60)); then
            echo " Giving up." 1>&2
            exit 2
        fi

	printf '.'
        sleep 2
    done
    # TODO: This leaves stray newlines.
    echo
}


wait_for_phone_to_be_in_fastboot() {
    SECONDS=0
    until check_phone_is_in_fastboot_mode; do

	if [ "$SECONDS" -eq 0 ]
	then
	    printf 'Waiting for the boot loader.'
	fi


        if ((SECONDS > 60)); then
            echo " Giving up" 1>&2
            exit 2
        fi

	printf '.'
        sleep 2
    done
    # TODO: This leaves stray newlines.
    echo
}

flash_patched_boot_image() {
    section Flashing patched boot image
    run_adb reboot bootloader
    wait_for_phone_to_be_in_fastboot
    # TODO: check if sudo is neded; udev may have been set up.
    sudo fastboot -s "$PHONE_ADB_SERIAL_NUMBER" flash boot "${PATCHED_IMAGE_LOCAL}"
    sudo fastboot -s "$PHONE_ADB_SERIAL_NUMBER" reboot
}


test_adb_root_access() {
    if run_adb shell test -w /proc
    then
	return 0
    else
	return 1
    fi
}

enable_adb_root_access() {

    wait_for_phone_to_be_in_adb
    
    if test_adb_root_access
    then
	return 0
    fi

    run_adb root

     # This doesn't happen instantly after rooting.
    wait_for_phone_to_be_in_adb

    if ! test_adb_root_access
    then
	echo "ADB failed to go into root mode." 1>&2
	exit 1
    fi
}

cleanup_leftovers() {
    section Cleaning up  "${PHONE_DOWNLOAD_DIR}" on phone
    enable_adb_root_access
    SECONDS=0
    until run_adb shell test -d "${PHONE_DOWNLOAD_DIR}"
    do
	if [ "$SECONDS" -eq 0 ]
	then
	    printf 'Waiting for the SD card.'
	fi

        if ((SECONDS > 60)); then
            echo " Giving up." 1>&2
            exit 2
        fi

        printf '.'
        sleep 2
    done
    # TODO: This leaves stray newlines.
    echo

    run_adb shell rm -rf "${UNPATCHED_IMAGE}" "${PATCHED_IMAGE}"
}

main() {
    determine_device_serial_number
    check_phone_is_connected
    extract_boot_image_on_phone
    patch_boot_image_on_phone
    transfer_patched_boot_image_to_pc
    flash_patched_boot_image
    cleanup_leftovers
}

# Run the main only when this file is executed as script, to help with testing.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
